version: '3.1'

services:
  keg-auth-pg:
    image: postgres:12-alpine
    container_name: keg-auth-pg
    environment:
      POSTGRES_DB: kegauth_tests
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    # This might not be what you want, use docker-compose.override.yml to change.
      - '127.0.0.1:5432:5432'
