version: 2
jobs:
    build:
        docker:
            - image: level12/python-test-multi
            - image: postgres:12
              environment:
                POSTGRES_DB: kegauth_tests
                POSTGRES_HOST_AUTH_METHOD: trust
        steps:
            - checkout

            - run:
                name: folder listing for debugging
                command: ls -al

            - run:
                name: install tox
                command: pip install tox

            - run:
                name: version checks
                command: |
                    python --version
                    pip --version
                    virtualenv --version
                    tox --version

            - run:
                name: run tox
                command: tox

            - store_test_results:
                path: .circleci/test-reports/

            - run:
                name: push code coverage
                command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t 949f0bab-d58d-4b87-b398-6d0851c8814f
